### ISSUE TITLE
Include lib in luarocks

### ISSUE THREAD

**Issue by italonascimento** [bjornbytes/RxLove#2]
Hey, I'm wondering, wouldn't you consider distributing this lib via LuaRocks?

I'm building a simple reactive framework on top of LÖVE that has RxLua and RxLove as dependencies, and it would be much easier to distribute if all dependencies were listed in LuaRocks.

Thanks for the great work!

**Comment by bjornbytes** [comment]
Just published a rock, let me know if everything works out.  Thanks!

**Comment by italonascimento** [comment]
It's working! Thanks for the quick response! :)

Just noticed, though, that I'm having problems with the Rx Lua v0.0.2. I guess it's just because it's outdated, since the source version was working fine. Not sure if I should open an issue about it in Rx Lua repo.

The error I'm getting is:

`attempt to call field 'of' (a nil value)`

**Comment by bjornbytes** [comment]
I'll try to get 0.0.3 published soon!

**Comment by italonascimento** [comment]
Nice! I'd be glad to help if there's anything I can do. :)
